// --- GAME CONFIGURATION ---
export const GAME_CONFIG = {
  GOD_MODE: true,
  SHOW_JUMP_LINE: true,

  GRAVITY: 0.8,
  JUMP_FORCE: -12.2,
  BASE_SPEED: 7.5,
  SPEED_MULTIPLIER: 1.25,
  SPAWN_RATE_BASE: 75,
  PLAYER_SIZE: 24,
  HITBOX_PADDING: 5,
  JUMP_BUFFER_TIME: 150,
  FLOAT_HEIGHT: 70,

  METERS_PER_LEVEL: 300,
  PIXELS_TO_METERS: 0.015,

  WIDTH: 400,
  HEIGHT: 600,
  FLOOR: 500,
  MID: 200,
} as const;
