// --- GAME CONFIGURATION ---
export const GAME_CONFIG = {
  GOD_MODE: false,
  SHOW_JUMP_LINE: false,

  GRAVITY: 0.68,
  JUMP_FORCE: -11.2,
  MAX_FALL_SPEED: 15,         
  JUMP_RELEASE_DAMPING: 0.9,
  BASE_SPEED: 7.5,
  SPEED_MULTIPLIER: 1.25,
  SPAWN_RATE_BASE: 75,
  PLAYER_SIZE: 24,
  HITBOX_PADDING: 5,
  JUMP_BUFFER_TIME: 150,
  FLOAT_HEIGHT: 70,

  METERS_PER_LEVEL: 300,
  PIXELS_TO_METERS: 0.015,

  WIDTH: 400,
  HEIGHT: 600,
  FLOOR: 500,
  MID: 200,
} as const;

export const {
  GOD_MODE,
  SHOW_JUMP_LINE,
  GRAVITY,
  JUMP_FORCE,
  MAX_FALL_SPEED,
  JUMP_RELEASE_DAMPING,
  BASE_SPEED,
  SPEED_MULTIPLIER,
  SPAWN_RATE_BASE,
  PLAYER_SIZE,
  HITBOX_PADDING,
  JUMP_BUFFER_TIME,
  FLOAT_HEIGHT,
  METERS_PER_LEVEL,
  PIXELS_TO_METERS,
  WIDTH,
  HEIGHT,
  FLOOR,
  MID,
} = GAME_CONFIG;
